<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>Rank Master 2</ApplicationTitle>
    <RootNamespace>RankMaster2</RootNamespace>
    <AssemblyName>RankMaster2</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>
  <Target Name="DropLibVlcX86" AfterTargets="ResolvePackageAssets">
    <ItemGroup>
      <Content Remove="libvlc\win-x86\**" />
      <None Remove="libvlc\win-x86\**" />
    </ItemGroup>
  </Target>
  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RankMaster2.Core\RankMaster2.Core.csproj" />
    <ProjectReference Include="..\RankMaster2.Ranking\RankMaster2.Ranking.csproj" />
    <ProjectReference Include="..\RankMaster2.Catalog\RankMaster2.Catalog.csproj" />
  </ItemGroup>
</Project>
