#!/usr/bin/env bash
# D-video.md § 6.2: the 4K AV1 fixtures the container tests need, generated by host ffmpeg (present
# on this build box: dav1d/svt-av1-enabled ffmpeg 7). Output is git-ignored — nothing here is a
# runtime dependency, exactly like tests/corpus/build-corpus.sh.
#
# The 8s 4K clips are the same encode § 4.3 measured on this box (testsrc2, SVT-AV1 preset 10,
# CRF 32, 161-frame closed GOP at 30fps -> -g 60 approximates the "gop size" the plan's ffmpeg
# numbers were taken from). A few small, fast clips are added so container test 1 can exercise all
# five containers without waiting on a second multi-minute 4K encode.
set -euo pipefail

OUT="${1:-$(cd "$(dirname "$0")" && pwd)/fixtures/video}"
mkdir -p "$OUT"
cd "$OUT"

say() { printf '  %-28s %s\n' "$1" "$2"; }

echo "4K AV1 (D-video.md § 4.3's measured encode):"
[ -s av1_4k_8bit.mp4 ] || ffmpeg -y -loglevel error -f lavfi -i "testsrc2=size=3840x2160:rate=30" \
  -t 8 -pix_fmt yuv420p -c:v libsvtav1 -preset 10 -crf 32 -g 60 av1_4k_8bit.mp4
say "av1_4k_8bit.mp4" "$(du -h av1_4k_8bit.mp4 | cut -f1)"

[ -s av1_4k_10bit.mp4 ] || ffmpeg -y -loglevel error -f lavfi -i "testsrc2=size=3840x2160:rate=30" \
  -t 8 -pix_fmt yuv420p10le -c:v libsvtav1 -preset 10 -crf 32 -g 60 av1_4k_10bit.mp4
say "av1_4k_10bit.mp4" "$(du -h av1_4k_10bit.mp4 | cut -f1)"

echo "Small fast clips, one per container (§ 6.2 test 1):"
CLIP="-f lavfi -i testsrc2=size=320x240:rate=30 -t 2 -an -y -loglevel error"
[ -s h264.mp4 ]  || ffmpeg $CLIP -c:v libx264 -preset veryfast -crf 30 h264.mp4
[ -s h264.mov ]  || ffmpeg $CLIP -c:v libx264 -preset veryfast -crf 30 h264.mov
[ -s h264.mkv ]  || ffmpeg $CLIP -c:v libx264 -preset veryfast -crf 30 h264.mkv
[ -s vp9.webm ]  || ffmpeg $CLIP -c:v libvpx-vp9 -crf 40 -b:v 0 vp9.webm
[ -s mpeg4.avi ] || ffmpeg $CLIP -c:v mpeg4 -q:v 8 mpeg4.avi
[ -s hevc.mp4 ]  || ffmpeg $CLIP -c:v libx265 -preset veryfast -crf 30 hevc.mp4
say "containers" "$(ls h264.mp4 h264.mov h264.mkv vp9.webm mpeg4.avi hevc.mp4 2>/dev/null | wc -l) files"

echo "Broken / edge fixtures (§ 6.2's generated set):"
[ -s audio_only.mp4 ] || ffmpeg -y -loglevel error -f lavfi -i "sine=frequency=440:duration=2" audio_only.mp4
printf 'not a video, just text wearing an mp4 extension' > text_pretending.mp4
: > empty.mp4
[ -s h264.mp4 ] && head -c 1500 h264.mp4 > truncated.mp4
say "broken/edge" "$(ls audio_only.mp4 text_pretending.mp4 empty.mp4 truncated.mp4 2>/dev/null | wc -l) files"

echo "Done: $OUT"
